enableTelemetry: false

nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://mirrors.cloud.tencent.com/npm/"

preferInteractive: true

preferReuse: true

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.9.1.cjs
