enableTelemetry: false

nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://registry.npmmirror.com"

preferInteractive: true

preferReuse: true

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.9.1.cjs
