version: '3.7'

services:
    
  # Warning: mongodb here is not password-protected.
  # DO NOT EXPOSE THIS SERVICE TO THE PUBLIC.
  oj-mongo:
    image: mongo
    container_name: oj-mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  oj-backend:
    image: hydrooj/hydro
    container_name: oj-backend
    restart: always
    build: ./backend
    depends_on:
      oj-mongo:
        condition: service_healthy
    volumes:
      - ./data/file:/data/file
      - ./data/backend:/root/.hydro
    network_mode: "host"
    environment:
      - HYDRO_HOST=0.0.0.0
      - HYDRO_PORT=2333

  oj-judge:
    build: ./judge
    container_name: oj-judge
    restart: always
    privileged: true
    depends_on:
      - oj-backend
    volumes:
      - ./data/judge:/root/.config/hydro
    network_mode: "host" 