services:
  # Warning: mongodb here is not password-protected.
  # DO NOT EXPOSE THIS SERVICE TO THE PUBLIC.
  oj-mongo:
    image: mongo
    container_name: oj-mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  oj-backend:
    image: hydrooj/hydro
    container_name: oj-backend
    restart: always
    build: ./backend
    depends_on:
      oj-mongo:
        condition: service_healthy
    volumes:
      - ./data/file:/data/file
      - ./data/backend:/root/.hydro
    ports:
      - "0.0.0.0:8080:8888"
    environment:
      - HYDRO_HOST=0.0.0.0
      - HYDRO_PORT=8888
    healthcheck:
      test: curl --silent --fail http://localhost:8888/status >/dev/null || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 5s

  oj-judge:
    build: ./judge
    container_name: oj-judge
    restart: always
    privileged: true
    depends_on:
      oj-backend:
        condition: service_healthy
        restart: true
    volumes:
      - ./judge/judge.yaml:/root/.hydro/judge.yaml
      - ./judge/mount.yaml:/root/.hydro/mount.yaml
